server.port=8085
spring.application.name=cart-service
# Database
spring.datasource.url=jdbc:h2:mem:cart-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Remote Services
product-service.url=http://localhost:8081
pricing-service.url=http://localhost:8086

# Resilience4j Configuration
resilience4j.circuitbreaker.instances.pricingService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.pricingService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.pricingService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.pricingService.waitDurationInOpenState=10000
